In [3]:
import ast
import pandas as pd
import pickle
import numpy as np


def parse_list(x):
    try:
        return ast.literal_eval(x)
    except (SyntaxError, ValueError):
        return x

# ml_1m_imdb

In [6]:
# pickle -> csv

# with open('ml_1m_imdb.pickle', 'rb') as f:
#     df = pickle.load(f)

# df.to_csv('ml_1m_imdb.csv', index=False)

df = pd.read_csv('ml_1m_imdb.csv')

df

,ml_id,imdb_id,ml_title,imdb_title,ml_year,imdb_year,ml_genres,ml_genres_augment,imdb_genres,imdb_type,...,writer,actor,actress,cinematographer,composer,producer,editor,production_designer,archive_footage,archive_sound
0,1,tt0114709,Toy Story (1995),Toy Story,1995,1995,"[Animation, Children's, Comedy]","[Adventure, Animation, Children, Comedy, Fantasy]","[Adventure, Animation, Comedy]",movie,...,"[nm0169505, nm0230032, nm0004056, nm0710020, n...","[nm0000158, nm0000741, nm0725543, nm0001815]",None,None,None,None,None,None,None,None
1,2,tt0113497,Jumanji (1995),Jumanji,1995,1995,"[Adventure, Children's, Fantasy]","[Adventure, Children, Fantasy]","[Adventure, Comedy, Family]",movie,...,"[nm0378144, nm0852430, nm0833164, nm0885575]","[nm0000245, nm0404993]","[nm0000379, nm0001372]",None,None,[nm0472256],None,None,None,None
2,3,tt0113228,Grumpier Old Men (1995),Grumpier Old Men,1995,1995,"[Comedy, Romance]","[Comedy, Romance]","[Comedy, Romance]",movie,...,[nm0425756],"[nm0000527, nm0000493]","[nm0000268, nm0000047]",[nm0005714],[nm0006293],"[nm0075828, nm0204862]",None,None,None,None
3,4,tt0114885,Waiting to Exhale (1995),Waiting to Exhale,1995,1995,"[Comedy, Drama]","[Comedy, Drama, Romance]","[Comedy, Drama, Romance]",movie,...,"[nm0573334, nm0060103]",None,"[nm0001365, nm0000291, nm0222643, nm0005375]",None,[nm0004892],"[nm0771834, nm0842470]",None,None,None,None
4,5,tt0113041,Father of the Bride Part II (1995),Father of the Bride Part II,1995,1995,[Comedy],[Comedy],"[Comedy, Family, Romance]",movie,...,"[nm0352443, nm0329304, nm0583600]","[nm0000188, nm0001737]","[nm0000473, nm0931090]",[nm0204567],[nm0006293],None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3878,3948,tt0212338,Meet the Parents (2000),Meet the Parents,2000,2000,[Comedy],[Comedy],"[Comedy, Romance]",movie,...,"[nm0322839, nm0164898, nm0381272, nm0357453]","[nm0001774, nm0000134]","[nm0001632, nm0001100]",None,None,[nm0742772],None,None,None,None
3879,3949,tt0180093,Requiem for a Dream (2000),Requiem for a Dream,2000,2000,[Drama],[Drama],[Drama],movie,...,[nm0782968],"[nm0001467, nm0005541]","[nm0000995, nm0000124]",[nm0508732],[nm0543739],"[nm0914615, nm0922279]",None,None,None,None
3880,3950,tt0170691,Tigerland (2000),Tigerland,2000,2000,[Drama],[Drama],"[Drama, War]",movie,...,"[nm0458462, nm0570077]","[nm0268199, nm0205127, nm0004286, nm0347509]",None,None,None,"[nm0586969, nm0004927, nm0353187]",None,None,None,None
3881,3951,tt0202641,Two Family House (2000),Two Family House,2000,2000,[Drama],[Drama],"[Comedy, Drama, Romance]",movie,...,None,"[nm0728346, nm0176723]","[nm0531808, nm0621393]",[nm0562574],[nm0006059],"[nm0365478, nm0459754]",[nm0502601],None,None,None
3882,3952,tt0208874,"Contender, The (2000)",The Contender,2000,2000,"[Drama, Thriller]","[Drama, Thriller]","[Drama, Thriller]",movie,...,None,"[nm0000198, nm0000313, nm0000225]",[nm0000260],None,[nm0343935],"[nm0126653, nm0296827, nm0818657, nm0881703]",None,None,None,None

# ml_100k_imdb

In [8]:
# pickle -> csv

# with open('ml_100k_imdb.pickle', 'rb') as f:
#     df = pickle.load(f)

# df.to_csv('ml_100k_imdb.csv', index=False)

df = pd.read_csv('ml_100k_imdb.csv')

df

,ml_id,imdb_id,ml_title,imdb_title,ml_year,imdb_year,ml_genres,imdb_genres,director,writer,actor,actress,cinematographer,composer,producer,editor,production_designer,archive_footage,archive_sound
0,1,tt0114709,Toy Story (1995),Toy Story,1995.0,1995.0,"['Animation', ""Children's"", 'Comedy']","['Adventure', 'Animation', 'Comedy']",['nm0005124'],"['nm0169505', 'nm0230032', 'nm0004056', 'nm071...","['nm0000158', 'nm0000741', 'nm0725543', 'nm000...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,tt0113189,GoldenEye (1995),GoldenEye,1995.0,1995.0,"['Action', 'Adventure', 'Thriller']","['Action', 'Adventure', 'Thriller']",['nm0132709'],"['nm0001220', 'nm0289833', 'nm0128997', 'nm027...","['nm0000112', 'nm0000293']","['nm0001713', 'nm0000463']",NaN,NaN,['nm0110483'],NaN,NaN,NaN,NaN
2,3,tt0113101,Four Rooms (1995),Four Rooms,1995.0,1995.0,['Thriller'],['Comedy'],"['nm0025978', 'nm0734319', 'nm0001675', 'nm000...",NaN,"['nm0000619', 'nm0000104']","['nm0205423', 'nm0004866']",NaN,NaN,['nm0004744'],NaN,NaN,NaN,NaN
3,4,tt0113161,Get Shorty (1995),Get Shorty,1995.0,1995.0,"['Action', 'Comedy', 'Drama']","['Comedy', 'Crime', 'Thriller']",['nm0001756'],"['nm0001465', 'nm0291082']","['nm0000432', 'nm0000362', 'nm0000237']",['nm0000623'],NaN,['nm0527099'],"['nm0787834', 'nm0792049']",NaN,NaN,NaN,NaN
4,5,tt0112722,Copycat (1995),Copycat,1995.0,1995.0,"['Crime', 'Drama', 'Thriller']","['Drama', 'Mystery', 'Thriller']",['nm0000750'],"['nm0081189', 'nm0535189']","['nm0000551', 'nm0001530']","['nm0000244', 'nm0000456']",NaN,['nm0002366'],"['nm0586969', 'nm0850516']",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,tt0119711,Mat' i syn (1997),Mother and Son,1998.0,1997.0,['Drama'],['Drama'],['nm0812546'],['nm0032685'],['nm0025651'],['nm0315407'],['nm0299513'],['nm0412155'],['nm0473983'],['nm0783978'],"['nm0954559', 'nm0728820']",NaN,NaN
1678,1679,tt0120594,B. Monkey (1998),B. Monkey,1998.0,1998.0,"['Romance', 'Thriller']","['Crime', 'Drama', 'Romance']",['nm0705535'],"['nm0203577', 'nm0454573', 'nm0859241']","['nm0364813', 'nm0000391', 'nm0001667']",['nm0000782'],NaN,NaN,"['nm0941262', 'nm0883267']",NaN,NaN,NaN,NaN
1679,1680,tt0120148,Sliding Doors (1998),Sliding Doors,1998.0,1998.0,"['Drama', 'Romance']","['Comedy', 'Drama', 'Fantasy']",['nm0398185'],NaN,"['nm0001314', 'nm0001487']","['nm0000569', 'nm0000675']",['nm0001899'],['nm0386595'],"['nm0104088', 'nm0394564', 'nm0001628']",NaN,NaN,NaN,NaN
1680,1681,tt0111804,You So Crazy (1994),Martin Lawrence: You So Crazy,1994.0,1994.0,['Comedy'],"['Comedy', 'Documentary']",['nm0772095'],NaN,NaN,NaN,['nm0016473'],NaN,"['nm0399144', 'nm0005604', 'nm0555684']","['nm0623628', 'nm0002377']",['nm0393922'],NaN,NaN
1681,1682,tt0102855,Scream of Stone (Schrei aus Stein) (1991),Scream of Stone,1996.0,1991.0,['Drama'],['Drama'],['nm0001348'],"['nm0459278', 'nm0768302', 'nm0313274', 'nm058...","['nm0583857', 'nm0323198', 'nm0915382']",['nm0000528'],NaN,NaN,['nm0486134'],NaN,NaN,NaN,NaN